export const REGISTER_USER_REQUEST: string = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS: string = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE: string = 'REGISTER_USER_FAILURE';