export const REGISTER_USER_REQUEST: string = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS: string = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE: string = "REGISTER_USER_FAILURE";

export const LOGIN_USER_REQUEST: string = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS: string = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE: string = "LOGIN_USER_FAILURE";