export const REGISTER_USER_REQUEST: string = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS: string = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE: string = "REGISTER_USER_FAILURE";

export const SUBSCRIBE_USER = "SUBSCRIBE_USER";

export const LOGIN_USER_REQUEST: string = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS: string = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE: string = "LOGIN_USER_FAILURE";

export const LOGOUT_USER: string = 'LOGOUT_USER';

export const GET_USER_BY_EMAIL_REQUEST = "GET_USER_BY_EMAIL_REQUEST";
export const GET_USER_BY_EMAIL_SUCCESS = "GET_USER_BY_EMAIL_SUCCESS";
export const GET_USER_BY_EMAIL_FAILURE = "GET_USER_BY_EMAIL_FAILURE";
export const SET_USER_BY_ID: string = "GET_USER_BY_ID";